import { app } from "electron";
import dotenv from "dotenv";
dotenv.config();

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  // eslint-disable-line global-require
  app.quit();
}

import { FsWatcher } from "../backend/fs-watcher";
import { setupRendererLogging } from "./logging";
import { createMainWindow } from "./window-creation";
import { setupAppEvents } from "./app-events";
import { setupSettingsHandlers } from "./ipc-handlers/settings-handlers";
import { setupFileHandlers } from "./ipc-handlers/file-handlers";
import { setupDialogHandlers } from "./ipc-handlers/dialog-handlers";
import { setupDownloadHandlers } from "./ipc-handlers/download-handlers";
import { setupRepoHandlers } from "./ipc-handlers/repo-handlers";

// Setup logging early, before windows are created
setupRendererLogging();

// Initialize application
const fsWatcher = new FsWatcher(app);

const createWindow = async () => {
  const mainWindow = createMainWindow(fsWatcher);

  // Setup all IPC handlers
  setupSettingsHandlers(mainWindow);
  setupFileHandlers(mainWindow, fsWatcher);
  setupDialogHandlers(mainWindow);
  setupDownloadHandlers(mainWindow, fsWatcher);
  setupRepoHandlers();
};

// Setup app event handlers
setupAppEvents(createWindow);

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
